name: Docker Build, Push and Deploy

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t miamotos/cicd:cicd .

    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Push Docker image to Docker Hub
      run: docker push miamotos/cicd:cicd

    - name: SSH into server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          # Подключение к серверу по SSH и выполнение команд
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker pull miamotos/cicd:cicd
          docker run -d -p 8080:80 miamotos/cicd:cicd

    - name: Update Docker image on server
      run: |
        docker pull miamotos/cicd:cicd
        docker stop my-app || true
        docker rm my-app || true
        docker run -d --name my-app -p 80:80 miamotos/cicd:cicd
