name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - master

env:
  DOCKER_HUB_USERNAME: miamotos
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
  SSH_KEY: ${{ secrets.SSH_KEY }}
  SSH_HOST: 192.168.24.129
  SSH_USERNAME: uri

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_HUB_USERNAME }}/my-docker-image:latest
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_PASSWORD }}

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USERNAME }}
          key: ${{ env.SSH_KEY }}
          script: |
            docker stop my-docker-container || true
            docker rm my-docker-container || true
            docker pull ${{ env.DOCKER_HUB_USERNAME }}/my-docker-image:latest
            docker run -d --name my-docker-container -p 8080:80 ${{ env.DOCKER_HUB_USERNAME }}/my-docker-image:latest
